spring:
  cloud:
    stream:
      function.definition: aggregate;testSource;testSink
      bindings:
        aggregate-out-0:
          destination: transformed
        testSink-in-0:
          destination: transformed
        aggregate-in-0:
          destination: testtock
        testSource-out-0:
          destination: testtock

solace:
  java:
    host: localhost
    msgVpn: default
    clientUsername: default
    clientPassword: default
    connectRetries: -1
    reconnectRetries: -1

