spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mysql
    username: root
    password: yolo69
    driver-class-name: org.mariadb.jdbc.Driver
spring.cloud.stream.bindings.input.destination: sample-sink-data
spring.cloud.stream.bindings.output.destination: sample-sink-data

solace:
  java:
    host: localhost
    msgVpn: default
    clientUsername: default
    clientPassword: default
    connectRetries: -1
    reconnectRetries: -1

